### ISSUE TITLE
无法push到阿里云oss bucket

### ISSUE THREAD

**Issue by shimingliangdm** [zhxxch/git-lfs-one#2]
大佬，我试了一下，但貌似没有成功push到阿里云的oss bucket里面，我想应该是url那里有问题，以下是我的.lfsconfig文件：
[lfs]
	url = https://***:***@******.cn-shenzhen.fc.aliyuncs.com/2021-01-05/proxy/git-lfs-bcd0/lfs/Repo.git/info/lfs

关于这个地址有几个问题，那个日期我看到你是直接写在资源栈文件里的（你的是2016-08-15），然后git-lfs-bcd0我看你的代码是截取了stackid加上去的，我不太明白这个stackid是阿里云根据我们申请的资源自动帮我们生成的还是怎样？还有现在2021年跟2016年这个资源栈模板格式是否还能用？

**Comment by zhxxch** [comment]
1. 我解释一下2016-08-15这个日期：这日期也直接写在阿里云发布的各种SDK里，目前是固定的，不过我可以替您问一下今后会不会变；您在控制台的触发器管理页面大概也会见到这个日期；
2. stackid的问题：这是阿里云自动生成的，我截取用来避免名字冲突；
3. 如果没有push成功，git lfs命令应该会显示错误信息，希望您提供相关错误信息；您不应该将lfs的远程url明文贴到这里，这个url可能暴露您的LFS用户名、密码以及阿里云用户ID，您试试能不能编辑掉。

**Comment by shimingliangdm** [comment]
可以了，感谢大佬的回复！
