### ISSUE TITLE
fc现在支持挂载OSS文件系统了。

### ISSUE THREAD

**Issue by oOtroyOo** [zhxxch/git-lfs-one#3]
https://help.aliyun.com/document_detail/454199.html

**Comment by zhxxch** [comment]
同志，你可能对本软件的原理有误解。LFS文件不经过fc，是直连OSS上传下载的。

**Comment by zhxxch** [comment]
同志，你可能对本软件的原理有误解。LFS文件不经过fc，是直连OSS上传下载的。
