### ISSUE TITLE
[Git LFS One] 如何关闭 git push 过程中向 GitHub 自动上传 LFS 文件？

### ISSUE THREAD

**Issue by Dragon1573** [zhxxch/git-lfs-one#4]
## 问题

将 Git LFS One 与 OneDrive 成功关联后，无法使用提供的 `lfs.v.ariant.cn` 域名链接实现 Git Pull 或 Git Push

## 复现

1. 关联 OneDrive 与 Git LFS One ，在本地 OneDrive 挂载目录下出现 `D:\OneDrive\应用\Git-LFS-One` 目录
   ![image](https://user-images.githubusercontent.com/49941141/220819563-6fe682ab-9415-47a6-998e-31c0da3e8356.png)
2. 在此目录打开 Git Bash ，执行 `git init --bare LFS` 初始化仓库，并在仓库内执行 `git lfs install` 安装 LFS Hooks
   ![image](https://user-images.githubusercontent.com/49941141/220822116-70e3fc5f-186d-4ed8-9004-379e4280ae4f.png)
3. 启动 WSL2 ，使用提供的在线域名执行 `git clone` 操作，出现异常
   ![image](https://user-images.githubusercontent.com/49941141/220822842-25aa6b01-6120-4e8a-a74e-5f0e3f94b0b5.png)
4. 使用 Drvfs 指定本地 OneDrive 挂载目录执行 `git clone` ，可以 Clone 成功
   ![image](https://user-images.githubusercontent.com/49941141/220823379-0864004c-1049-44fb-ac30-e77b0d99a314.png)
   ![image](https://user-images.githubusercontent.com/49941141/220823478-1701548e-8f5d-4a5e-9915-952027792fb4.png)

**Comment by zhxxch** [comment]
git仓库请另行托管，本应用仅服务于git-lfs，不提供git托管服务。

因此本应用提供的链接不支持git协议，只支持git-lfs协议，仅能作为git-lfs的远程地址（git术语叫remote），不能作为git的远程地址（remote）。

本应用提供的地址添加作为远程地址（remote）之后，仅供`git lfs`系列命令使用，例如`git lfs fetch <remote-name>`，不支持`git`系列命令，例如`git fetch <remote-name>`、`git clone <remote-url>`。

请参考[使用协议](https://lfs-one.inv.ariant.cn/Terms-of-Use)第5条。根据git-lfs设计上的特性，只有拥有git仓库本身后才能访问git-lfs文件，因此本应用不另设访问控制，用户需要自己管理git仓库本身的托管和访问控制。

**Comment by Dragon1573** [comment]
> Git 仓库请另行托管，本应用仅服务于 Git LFS ，不提供 Git 托管服务。

当前，我已用 GitHub 托管 Git 仓库本体，仅在初次提交时包含了 `.gitattributes` 文件。在使用 OneDrive 的 Drvfs 本地挂载目录作为 Remote 时，可以正常执行 `git lfs push onedrive` 和 `git push --verbose --progress onedrive main` 。

但另外 Clone GitHub 仓库至本地并添加 Git LFS One 链接作为 Remote ，执行 `git lfs fetch onedrive` 仅有如下提示，执行 `git lfs pull onedrive` 无任何回显，LFS 文件本体（10.0MB）也未正确获取到本地。

```text
20:57:57 ~/D/lfs-two-backend 2ms $ git lfs fetch --all onedrive                                                                                       main
fetch: Fetching all references...
20:58:00 ~/D/lfs-two-backend 17ms $ git lfs pull onedrive                                                                                             main
21:01:04 ~/D/lfs-two-backend 15ms $                                                                                                                   main
```

作为本地主仓（`lfs-one-backend/`）和本地副本仓（`lfs-two-backend/`）内容如下：

<details>
<summary>主仓</summary>

```text
21:04:34 ~/D/lfs-one-backend 1ms $ git log --graph                                                                                                  main ⬆
* commit ba23481bebc6481ec92dde9f07455398d4f66630 (HEAD -> main, onedrive/main)
| Author: Dragon1573 <49941141+Dragon1573@users.noreply.github.com>
| Date:   Sat Feb 25 20:48:50 2023 +0800
|
|     添加大文件，上传到 OneDrive
|
* commit 32313184e27eb9970c181ccd42cbc67834320c06 (github/main, github/HEAD)
  Author: Dragon1573 <49941141+Dragon1573@users.noreply.github.com>
  Date:   Sat Feb 25 20:16:09 2023 +0800

      首次提交：启用 Git LFS 大文件
21:04:38 ~/D/lfs-one-backend 9ms $ git remote -v                                                                                                    main ⬆
github  git@github.com:Dragon1573/lfs-one-backend.git (fetch)
github  git@github.com:Dragon1573/lfs-one-backend.git (push)
onedrive        /mnt/d/OneDrive/应用/Git-LFS-One/lfs-one-backend (fetch)
onedrive        /mnt/d/OneDrive/应用/Git-LFS-One/lfs-one-backend (push)
21:04:45 ~/D/lfs-one-backend 2ms $ la                                                                                                               main ⬆
总用量 11M
drwxr-xr-x 9 dragon1573 dragon1573 4.0K  2月 25 21:04 .git/
-rw-r--r-- 1 dragon1573 dragon1573   42  2月 25 20:40 .gitattributes
-rw-r--r-- 1 dragon1573 dragon1573  10M  2月 25 20:48 random.bin
```

</details>
<details>
<summary>副本仓</summary>

```text
21:05:20 ~/D/lfs-two-backend 1ms $ git log --graph                                                                                                    main
* commit 32313184e27eb9970c181ccd42cbc67834320c06 (HEAD -> main, github/main, github/HEAD)
  Author: Dragon1573 <49941141+Dragon1573@users.noreply.github.com>
  Date:   Sat Feb 25 20:16:09 2023 +0800

      首次提交：启用 Git LFS 大文件
21:05:23 ~/D/lfs-two-backend 9ms $ git remote -v                                                                                                      main
github  git@github.com:Dragon1573/lfs-one-backend.git (fetch)
github  git@github.com:Dragon1573/lfs-one-backend.git (push)
onedrive        https://lfs.v.ariant.cn/LWH8mdMv8gs/lfs-one-backend.git (fetch)
onedrive        https://lfs.v.ariant.cn/LWH8mdMv8gs/lfs-one-backend.git (push)
21:05:29 ~/D/lfs-two-backend 2ms $ la                                                                                                                 main
总用量 8.0K
drwxr-xr-x 9 dragon1573 dragon1573 4.0K  2月 25 21:05 .git/
-rw-r--r-- 1 dragon1573 dragon1573   42  2月 25 20:54 .gitattributes
```

</details>

若执行 `git push --verbose --progress github` ，那么再推送时会将 LFS 文件也上传到 GitHub 中。

**Comment by Dragon1573** [comment]
经测，必须当 Git 仓库处于包含了 Git LFS 内容的 Commit 下，执行 `git lfs fetch --all onedrive` 和 `git lfs checkout` 是能够正常从 Git LFS One 获取大文件的。

现在的问题转变为： **如何关闭向 GitHub LFS 的自动 Push ？** 我必须将此 Commit 提交到 GitHub ，但又必须阻止 `git push --verbose --progress github` 时自动触发 Hooks 执行 `git lfs push --all github` 。

**Comment by zhxxch** [comment]
> 经测，必须当 Git 仓库处于包含了 Git LFS 内容的 Commit 下，执行 `git lfs fetch --all onedrive` 和 `git lfs checkout` 是能够正常从 Git LFS One 获取大文件的。

这是正常的，git-lfs的工作原理决定了这个行为。

> 现在的问题转变为： **如何关闭向 GitHub LFS 的自动 Push ？** 我必须将此 Commit 提交到 GitHub ，但又必须阻止 `git push --verbose --progress github` 时自动触发 Hooks 执行 `git lfs push --all github` 。

问题和本应用无关。

**Comment by Dragon1573** [comment]
> 问题和本应用无关

问题已解决！

经查阅 [文档](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-config.adoc#list-of-options) ，有以下几种方式来指定 Git LFS Remote 。

1. 使用 `git config --local remote.github.lfsurl` 指定 `github` 这个 Clone URL 地址关联的 Git LFS Remote ，此设置默认为空并从 Clone URL 中自动分析获得
   > 可以使用 `git config --local remote.github.lfspushurl` 额外 `github` 这个 Git Remote 关联的 Git LFS Push Remote ，此设置默认为空并从 Non-Push URL 或者 Clone URL 中获得
2. 使用 `git config --local lfs.url` 和 `git config --local lfs.pushurl` 为所有 Clone URL 指定统一的 Git LFS Remote URL
3. 使用 `git remote add onedrive ...` 添加 OneDrive Remote URL ，随后使用 `git config --local remote.lfsdefault` 和 `git config --local remote.lfspushdefault` 指定 Git LFS 的默认远程地址。

![image](https://user-images.githubusercontent.com/49941141/221367197-cb1f1b1c-6414-4bfb-8c66-1a2277d38bd2.png)

*****

在使用方法一修改配置后，正常执行 `git push` 操作，LFS 文件能够正常被一并上传。检查 GitHub 仓库，LFS 文件仅为指针文件格式，没有提示此文件正在使用 LFS 存储。

![image](https://user-images.githubusercontent.com/49941141/221366943-9a9c2c03-9445-42ac-89ba-ad88c9bb3bd3.png)

![image](https://user-images.githubusercontent.com/49941141/221367009-6aecc0e7-02e5-4e76-86e1-eb36b221f1eb.png)

检查 OneDrive 本地挂载目录，可以看到 LFS 对象已正确上传。

![image](https://user-images.githubusercontent.com/49941141/221367095-875b635e-d7d1-4c58-b101-0f7703d8039f.png)
